# Generated by Django 5.2.3 on 2025-06-16 16:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='renovacao',
            new_name='renovado',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='password',
            new_name='senha',
        ),
        migrations.RenameField(
            model_name='leitor',
            old_name='nome_completo',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leitor',
            name='data_nascimento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leitor',
            name='endereco',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='leitor',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={},
        ),
        migrations.AlterModelManagers(
            name='funcionario',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='username',
        ),
        migrations.AddField(
            model_name='livro',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
